apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: myapp-deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp 
  strategy:
    type: RollingUpdate 
    rollingUpdate: 
      maxUnavailable: 1   # At most 1 pod down during update
      maxSurge: 1         # At most 1 extra pod above desired
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container 
          image: nginx:latest 
          ports: 
          - containerPort: 80


# RollingUpdate: Gradually replace pods with the new image.

# maxUnavailable/maxSurge: Control downtime vs. resource spike.


# Commands:
#a. kubectl set image deployment/myapp-deployment myapp-container=myapp:v2
#b. kubectl rollout status deployment/myapp-deployment
#c. kubectl rollout undo deployment/myapp-deployment


# Meaning: Update your app version without downtime, and easily roll back if things break.

