apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: data-app
spec:
  clusterIP: None            # No virtual IP
  selector:
    app: mongo
  ports:
    - port: 27017
      name: mongo

