apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: demo-app 
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend 
        image: saikiran8050/demo-backend:latest
        command: ["node","server.js"]
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"