# k8s/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: recreate-demo
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-docker-repo/backend:latest
        env:
        - name: PG_HOST
          value: postgres.recreate-demo.svc.cluster.local
        - name: PG_USER
          value: demo
        - name: PG_PASSWORD
          value: demo
        - name: PG_DATABASE
          value: demo
        ports:
        - containerPort: 3000
