apiVersion: v1 # Kubernetes API version
kind: Service # Resource type
metadata:
  name: my-service # Service name
  labels:
    app: web 
spec:
  selector: #How to find target Pods
    app: web 
  ports: # Port configuration 
  - port: 80   # Service port (what clients connect to)
    targetPort: 8080 # Pod port (where app actually runs)
  type: ClusterIP # Service type (default)


# Key Components:
# port: The port clients use to connect to the Service
# targetPort: The actual port your application listens on inside the Pod
# selector: Labels that identify which Pods this Service routes to

