apiVersion: v1 
kind: Service 
metadata: 
  name: production-web 
spec: 
  type: LoadBalancer 
  selector: 
    app: web 
  ports: 
  - port: 80
    targetPort: 8080 


# Use Case: Production web applications, public-facing services