apiVersion: v1
kind: Service 
metadata:
  name: multi-port-service 
spec: 
  selector:
    app: web-app
  ports:
  - name: http # Named port for clarity
    port: 80 
    targetPort: 8080 
    protocol: TCP
  - name: https 
    port: 443
    targetPort: 8443
    protocol: TCP
  - name: metrics 
    port: 9090 
    targetPort: 9090  
    protocol: TCP