apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  clusterIP: None              # No virtual IP - returns Pod IPs directly
  selector:
    app: database
  ports:
    - port: 5432
      targetPort: 5432


# Use Case: StatefulSets, database clusters, service discovery