version: "3"
services:
  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    volumes:
      - ./mongo-data:/data/db
    networks:
      - appnet

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/notesapp
      - JWT_SECRET=mysupersecretjwt
    depends_on:
      - mongo
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "3002:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

