apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: my-pvc
spec:
  accessModes: 
    - ReadWriteOnce     # Only one Pod can write
  resources:
    requests:
      storage: 1Gi     # Requesting 1 GiB of storage  