apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
  name: database 
spec: 
  serviceName: database-service 
  replicas: 3 
  selector: 
    matchLabels: 
      app: database  
  template: 
    metadata: 
      labels: 
        app: database
    spec: 
      containers:
      - name: db 
        image: postgres:13 
        volumeMounts: 
        - name: data 
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates: 
  - metadata: 
      name: data 
    spec: 
      accessModes: 
      - ReadWriteOnce 
      storageClassName: fast-storage 
      resources:
        requests: 
          storage: 100Mi
